apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-jjohnson-ah
  namespace: argocd-test
spec:
  project: enbl6682
  source:
    repoURL: https://github.com/jjohnson-ah/jjohnson-argocd-tags.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
