apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-tags
  namespace: argocd
spec:
  project: sample
  source:
    repoURL: https://github.com/jjohnson/jjohnson-argocd-tags
    targetRevision: my-tag
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
